#!/bin/sh

if [ x"$1" = x"sh" -o x"$1" = x"bash" ]; then
  exec $@
  exit
fi

[ ! -e /logstash/config/logstash.yml ] \
  && echo "Generating configs" \
  && cp -R /logstash/config.orig/* /logstash/config/

[ ! -e /logstash/pipeline -o `ls /logstash/pipeline 2>/dev/null | wc -l` == '0' ] \
  && mkdir /logstash/pipeline \
  && echo >/logstash/pipeline/00-default <<EOF
input {
  stdin {}
}
output {
  stdout {}
}
EOF

chown -R logstash:logstash /logstash/config
chown -R logstash:logstash /logstash/pipeline
chown -R logstash:logstash /logstash/data
chown -R logstash:logstash /logstash/logs

exec su logstash -c "logstash/bin/logstash -f /logstash/pipeline $@"
